#!/bin/bash
#PBS -l nodes=1:ppn=4,vmem=30gb,walltime=4:00:00
#PBS -N app-filterViaQuickbundles

# run cull

SINGULARITYENV_PYTHONNOUSERSITE=true singularity exec -e docker://brainlife/pyafq:dev ./initialSegmentation.py

if [ -f track.tck ]; then
	echo "complete"
	exit 0
else
	echo "failed"
	exit 1
fi
